dist: bionic
language: c++
submodules:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - python3-pip
branches:
  only:
    - main
before_script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-8
  - export CXX=g++-8
  - python3 -m pip install --quiet --upgrade pip
  - pip3 install --user torch torchvision torchaudio
  - mkdir build && cd build
  - cmake .. -DTORCH_DIR=`pip3 show torch | grep Location | cut -d ":" -f 2`/torch -DCMAKE_INSTALL_PREFIX=$HOME/torch_monitor ..
  - make install -j8
  - cd ../driver
  - make TORCH_MONITOR_DIR=$HOME/torch_monitor
  - cd ..
script:
  - cd test
  - ./test_add.sh