dist: bionic
language: c++
submodules:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
branches:
  only:
    - main
before_script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-8
  - export CXX=g++-8
  - pyenv install 3.8.5
  - pyenv global 3.8.5
  - python -m ensurepip --upgrade
  - pip install torch torchvision torchaudio
  - export TORCH_DIR=`pip show torch | grep Location | cut -d ":" -f 2`/torch
  - export TORCH_DIR=`echo $TORCH_DIR | xargs echo -n`
  - make TORCH_DIR=$TORCH_DIR -j8
  - make install PREFIX=$HOME/torch_monitor
  - cd driver
  - make TORCH_MONITOR_DIR=$HOME/torch_monitor
  - cd ..
script:
  - cd test
  - ./test_add_cpu.sh
  - ./test_mnist_cpu.sh
  - ./test_resnet_cpu.sh
